apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pv-claim
  labels:
    app: minio-localvolume-claim
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: localvolume
  resources:
    requests:
      storage: 2Gi
