apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv
  labels:
    app: minio-localvolume-claim
    type: localvolume
spec:
  storageClassName: localvolume
  claimRef:
    name: minio-pv-claim
    namespace: default
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /home/ubuntu/data # Specify a path to a local drive or volume on the Kubernetes worker node
    type: DirectoryOrCreate # The path to the last directory must exist
